theme = "tokyonight_storm"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
auto-format = true
auto-save = true
scrolloff = 8
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
Y = ":clipboard-yank"
C-h = ":buffer-previous"
C-j = "half_page_down"
C-k = "half_page_up"
C-l = ":buffer-next"

[keys.normal.space]
q = ":quit"
w = ":write"

[keys.insert]
C-space = "completion"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "·"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true