[[language]]
name = "vue"
file-types = ["vue"]
language-server = { command = "vue-language-server", args = ["--stdio"] }
scope = "text.html.vue"
roots = ["package.json"]
auto-format = true
injection-regex = "vue"

[[grammar]]
name = "vue"
source = { git = "https://github.com/xiaoxin-sky/tree-sitter-vue", rev = "8bbcd4cbd59c03b895d226c272e3c835f4329eef" }

[language.config.typescript] # this part must be hardcoded sadly, if anyone figures out how to provide a relative path let me know
tsdk = "/Users/reynardlee/.nvm/versions/node/v18.9.1/lib/node_modules/typescript/lib"
roots = [ "tsconfig.json"]

[language.config.languageFeatures]
semanticTokens = false
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true
    
[language.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }
